/** Built-in rule count — keep in sync with packages/dbt-doctor-rules rule registry. */
export const BUILTIN_RULE_COUNT = 191;

/**
 * Governance / architecture rules folded into the demo score (not shown in the animation).
 * All ids must exist in dbt-doctor-rules ALL_DBT_DOCTOR_RULE_KEYS.
 */
export const HIDDEN_GOVERNANCE_RULE_IDS = [
  "staging-prefix",
  "staging-naming-convention",
  "staging-materialized-view",
  "intermediate-prefix",
  "marts-prefix",
  "generic-test-present",
  "direct-source-and-ref",
  "prefer-ref-over-raw-source",
  "dbt-project-name",
  "bigquery-partition-filter",
  "materialization-hint",
  "empty-model-file",
  "jinja-config-block",
  "rejoining-upstream-concepts",
  "root-models",
  "source-has-loader",
  "model-has-meta-keys",
  "model-has-uniqueness-test",
  "model-single-pk-column-level",
  "per-model-schema-yml",
  "model-has-example-sql",
  "model-contract-enforced",
  "source-has-tests",
  "macro-has-meta-keys",
  "jinja-tag-padding",
] as const;

/**
 * Native SQL style rules (sql-style tag). Replaces legacy sqlfluff/* keys in the demo score.
 */
export const HIDDEN_SQL_STYLE_RULE_IDS = [
  "sql-alias-length-min",
  "sql-alias-not-keyword",
  "sql-ambiguous-distinct-group-by",
  "sql-ambiguous-join-type",
  "sql-ambiguous-order-by-target",
  "sql-between-symmetric-style",
  "sql-boolean-comparison-simplify",
  "sql-boolean-literal-style",
  "sql-boolean-null-case",
  "sql-case-nesting",
  "sql-cast-style-consistency",
  "sql-clause-newline-consistency",
  "sql-coalesce-preferred",
  "sql-constant-expression",
  "sql-count-star-preferred",
  "sql-cte-blank-line-after",
  "sql-cte-bracket-position",
  "sql-data-type-case",
  "sql-derived-table-alias-required",
  "sql-distinct-parentheses",
  "sql-distinct-with-order-by-non-selected",
  "sql-explicit-column-alias",
  "sql-explicit-join-type",
  "sql-explicit-table-alias",
  "sql-expression-alias-required",
  "sql-file-trailing-newline",
  "sql-function-name-case",
  "sql-function-spacing",
  "sql-indentation-consistency",
  "sql-join-condition-in-on-clause",
  "sql-join-condition-required",
  "sql-join-using-consistency",
  "sql-keywords-case",
  "sql-leading-commas",
  "sql-max-consecutive-blank-lines",
  "sql-no-comma-join",
  "sql-no-consecutive-semicolons",
  "sql-no-else-null-case",
  "sql-no-leading-whitespace",
  "sql-no-positional-group-order",
  "sql-no-self-alias",
  "sql-no-subquery-in-join",
  "sql-null-comparison-operator",
  "sql-null-literal-style",
  "sql-operator-spacing",
  "sql-order-by-direction-consistency",
  "sql-order-by-distinct-compatibility",
  "sql-order-by-ordinal-unambiguous",
  "sql-prefer-bang-equals",
  "sql-quoted-literal-style",
  "sql-reference-consistency",
  "sql-reference-keyword-quoted",
  "sql-reference-object-in-from",
  "sql-reference-special-chars-quoted",
  "sql-reference-target-exists",
  "sql-reference-unnecessary-quoted",
  "sql-references-qualified",
  "sql-select-targets-layout",
  "sql-select-trailing-comma",
  "sql-self-join-alias-distinct",
  "sql-set-operator-column-count-match",
  "sql-set-operator-newline",
  "sql-simple-case-preferred",
  "sql-single-statement-model",
  "sql-trailing-commas",
  "sql-trailing-whitespace",
  "sql-tsql-bare-temp-table",
  "sql-tsql-sp-prefix",
  "sql-tsql-sys-schema-qualified",
  "sql-union-distinct-redundant",
  "sql-union-explicit-qualifier",
  "sql-unique-column-aliases",
  "sql-unique-table-aliases",
  "sql-unquoted-identifiers-case",
  "sql-unused-cte",
  "sql-unused-join-alias",
  "sql-zero-length-string-style",
] as const;
